### PR TITLE
Fix for error: 'module' object has no attribute 'CH_QFLT'

### PR DESCRIPTION
**Pull request by prusanov**
Fix for error: 'module' object has no attribute 'CH_QFLT' (tested on IDA 7.0 and 7.2)

### CODE REVIEW

**Comment by patois** [comment]
Thank you! I confirm it only worked with IDA 7.3+ prior to your fix.
